# .tarvis.yml
language: node_js # 指定语言环境
node_js:
  - 10 # 指定 nodejs 版本

sudo: false # 是否需要 sudo 权限

branches:
  only: 
  - source

before_install:
  - npm install -g hexo

install:
  - npm install
  
script:
  - git clone https://github.com/theme-next/hexo-theme-next themes/next
  - cp themes_config/next/_config.yml themes/next/
  - cp themes_config/next/languages/zh-CN.yml themes/next/languages/
  - hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  target_branch: master # 部署的目标分支，默认为 gh_pages 分支
  github-token: $GIT_REPO_TOKEN # 在 Travis CI 环境变量中添加的 github 访问令牌名
  keep-history: true
  on:
    branch: source # 源码分支
  local-dir: public # 要部署内容的目录

after_success:
# ### 打包成 war 包，通过 ftp 上传到服务器
  - jar -cvfM blog.war -C ./public/ . # 将 public 目录下所有文件打包到 blog.war 中
  # 上传 war 包到服务器
  - curl --ftp-create-dirs -u hexo:${FTP_PASS} -T ./blog.war ftp://118.24.50.165/blog.war
# ### 推送到 coding.net 
  - git config --local user.name "travis-ci"
  - git config --local user.email "deploy@travis-ci.org"
  - sed -i '/wqf31415.github.io.git,master/d' _config.yml
  - tail _config.yml
  - sed -i'' "s~https://e.coding.net/~https://${GIT_CODING_TOKEN_USERNAME}:${GIT_CODING_REPO_TOKEN}@wqf31415.coding.net/~" _config.yml
  - tail _config.yml
  - hexo deploy
  
notifications:
  email: 
    recipients:
      - wqf31415@hotmail.com
      - wqf31415@wqf31415.xyz
    on_success: change # default: change
    on_failure: always # default: always
  
  

