name: Deploy to Pages branch

on:
  push:
    branches:
      - source # code branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: npm install

      - name: download theme
        run: git clone https://github.com/next-theme/hexo-theme-next themes/next --depth=1

      - name: cp config file
        run: |
          cp themes_config/next/_config.yml themes/next/
          cp themes_config/next/languages/zh-CN.yml themes/next/languages/

      - name: Build
        run: npm run build

      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to pages branch
        run: |
          # Create a new git repo in public folder and force push to pages branch
          cd public
          git init
          git add -A
          git commit -m "github-actions: deployed $(date)"
          git push -f "https://${{ secrets.GITHUB_TOKEN }}@github.com/wqf31415/wqf31415.github.io.git" master:pages
